services:
  - type: web
    name: project-board-api
    env: node
    buildCommand: cd ../.. && pnpm install && pnpm --filter api build
    startCommand: cd apps/api && node dist/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_PORT
        value: 10000
      - key: FRONTEND_URL
        value: https://project-board-web.vercel.app
